Repository openhab/openhab-google-assistant, pull requests merged in 2021-05, with the labels that each got.

#204 Fix broken links
  docs/USAGE.md
Labels: documentation

#193 (WIP) Add deployment on tag
  .github/release-drafter.yml
  .github/workflows/ci-cd.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/test.yml
  functions/config.js
  package.json
  testServer.js
  tests/config.test.js
  tests/setenv.js
Labels: enhancement, work in progress

#207 Fix markdown warnings
  README.md
Labels: documentation

#200 Use package version as swVersion
  functions/devices/default.js
  tests/devices/default.test.js
  tests/openhab.test.js
Labels: enhancement

#211 Fix exception when tfa challenge is missing
  functions/commands/default.js
  tests/commands/default.test.js
Labels: bug

#210 Support types with dimension
  functions/devices/default.js
  functions/devices/openclosedevice.js
  tests/devices/default.test.js
  tests/devices/temperaturesensor.test.js
Labels: bug, enhancement

#194 Remove tag support
  docs/USAGE.md
  functions/apihandler.js
  functions/devices/default.js
  functions/devices/thermostat.js
  functions/openhab.js
  tests/apihandler.test.js
  tests/devices/default.test.js
  tests/devices/thermostat.test.js
  tests/openhab.test.js
Labels: enhancement
