Repository openhab/openhab-google-assistant, pull requests merged in 2021-11, with the labels that each got.

#269 Fix typos in usage documentation
  docs/USAGE.md
Labels: documentation

#270 Add markdown check workflow
  .github/release-drafter.yml
  .github/workflows/ci-cd.yml
  .github/workflows/draft-release.yml
  .markdownlint.yaml
  README.md
  docs/USAGE.md
  functions/utilities.js
  tests/openhab.test.js
Labels: enhancement, documentation

#274 Use node.js v14
  .github/workflows/ci-cd.yml
  README.md
Labels: enhancement, dependencies

#226 Enhanced SecuritySystem support
  .gitignore
  docs/USAGE.md
  functions/apihandler.js
  functions/commands/armdisarm.js
  functions/commands/default.js
  functions/commands/index.js
  functions/devices/default.js
  functions/devices/index.js
  functions/devices/securitysystem.js
  functions/devices/simplesecuritysystem.js
  functions/openhab.js
  tests/apihandler.test.js
  tests/commands/armdisarm.test.js
  tests/commands/default.test.js
  tests/commands/index.test.js
  tests/devices/index.test.js
  tests/devices/securitysystem.test.js
  tests/devices/simplesecuritysystem.test.js
  tests/openhab.test.js
Labels: enhancement

#277 Catch JSON parse error in apihandler
  functions/apihandler.js
  tests/apihandler.test.js
Labels: bug
