Repository openhab/openhab-google-assistant, pull requests merged in 2023-11, with the labels that each got.

#525 Add colorTemperatureInverted option
  docs/USAGE.md
  functions/commands/colorabsolutetemperature.js
  functions/devices/default.js
  functions/devices/specialcolorlight.js
  tests/commands/colorabsolutetemperature.test.js
  tests/devices/specialcolorlight.test.js
Labels: enhancement

#533 Bump prettier from 3.0.3 to 3.1.0 and fix issues
  functions/commands/default.js
  package-lock.json
  package.json
Labels: dependencies

#534 Parse states as float for Number:Dimensionless items with units
  functions/devices/charger.js
  functions/devices/climatesensor.js
  functions/devices/dimmablelight.js
  functions/devices/fan.js
  functions/devices/humiditysensor.js
  functions/devices/openclosedevice.js
  functions/devices/sensor.js
  functions/devices/speaker.js
  functions/devices/specialcolorlight.js
  functions/devices/tv.js
  tests/devices/charger.test.js
  tests/devices/climatesensor.test.js
  tests/devices/dimmablelight.test.js
  tests/devices/fan.test.js
  tests/devices/humiditysensor.test.js
  tests/devices/openclosedevice.test.js
  tests/devices/sensor.test.js
  tests/devices/speaker.test.js
  tests/devices/specialcolorlight.test.js
  tests/devices/tv.test.js
Labels: bug
